apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plaza

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: plaza
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/nizamiq/plaza
    newTag: "0.1.0"
