apiVersion: v1
kind: ServiceAccount
metadata:
  name: plaza
  namespace: plaza
  labels:
    app.kubernetes.io/name: plaza
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
