apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plaza-staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: plaza-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info

images:
  - name: ghcr.io/nizamiq/plaza
    newTag: staging-latest

commonLabels:
  environment: staging
